# Generated by Django 5.2.14 on 2026-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_purchase_supplier_medicine_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
