# Generated by Django 5.2.14 on 2026-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sale_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrecord',
            name='return_type',
            field=models.CharField(choices=[('SALES_RETURN', 'Sales Return (Customer to Pharmacy)'), ('PURCHASE_RETURN', 'Purchase Return (Pharmacy to Supplier)')], default='SALES_RETURN', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20),
        ),
    ]
