# Generated by Django 5.2.14 on 2026-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_returnrecord_return_type_alter_returnrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='COMPLETED', max_length=20),
        ),
    ]
