# Generated by Django 5.2.14 on 2026-06-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
